import { z } from "zod";
import { urlSchema } from "@/lib/validation/url";
import { isRenderableMediaUrl } from "@/lib/media/url";
import { EMBED_PROVIDERS, VIDEO_PROVIDERS, resolveEmbed } from "@/lib/embeds/providers";

/**
 * What each kind of block is allowed to contain.
 *
 * `blocks.data` is JSONB, which means it is whatever was last written to it —
 * by this editor, by a migration, or by somebody with the anon key and a
 * console open. None of that is a promise about its shape, so every read
 * validates and every write validates again.
 *
 * One schema per type, in one file, is the thing that makes the rest of the
 * feature small: the editor derives its defaults from here, the save action
 * parses against here, and the renderer receives a value it can destructure
 * without checking anything.
 *
 * A block whose data fails its schema is dropped rather than rendered. That is
 * the only honest answer — the page has no way to draw something it cannot
 * understand, and guessing would put unvalidated strings on screen.
 */

/* ── Shared pieces ────────────────────────────────────────────────────────── */

/**
 * An image that lives in our own Storage bucket.
 *
 * Not `urlSchema`: that accepts any http(s) address, and an image tag is a
 * request the server makes on a visitor's behalf. Restricting it to the
 * project's own bucket is what stops a creator from using a ShowMe page to
 * pull a tracking pixel — or to point the image optimizer at an arbitrary host.
 */
const storedImageUrl = z
  .string()
  .trim()
  .min(1)
  .max(2048)
  .refine(isRenderableMediaUrl, "That image is not stored on ShowMe.");

/**
 * Alt text.
 *
 * Optional, because a decorative image with an empty alt is correct markup and
 * forcing a description would produce screen-reader noise like "image123.jpg".
 * The editor asks for one and explains why; the schema does not insist.
 */
const altText = z.string().trim().max(200).default("");

const caption = z.string().trim().max(120).default("");

/** A button attached to a block: a label and somewhere safe to go. */
const callToAction = z
  .object({
    label: z.string().trim().min(1, "Give the button a label.").max(40),
    url: urlSchema,
  })
  .nullable()
  .default(null);

/* ── One schema per block type ────────────────────────────────────────────── */

/**
 * A links section.
 *
 * The links themselves are rows in the `links` table, not JSON in here: they
 * are first-class data that Phase 6's `link_clicks` will reference by id, and
 * burying them in a blob would make per-link analytics a rewrite. What the
 * block carries is only what belongs to the section itself.
 */
export const linksBlockSchema = z.object({
  /** An optional heading above the links — "Latest", "Shop", "Listen". */
  title: z.string().trim().max(60).default(""),
});

/**
 * The row of social marks.
 *
 * Reads `social_links` for the profile, for the same reason: one row per
 * platform, enforced by a unique index, so the set cannot disagree with itself
 * across two blocks.
 */
export const socialsBlockSchema = z.object({});

export const textBlockSchema = z.object({
  text: z.string().trim().min(1, "Write something.").max(1000),
  align: z.enum(["left", "center"]).default("center"),
  /*
   * Two styles, not a rich text editor. A heading and a paragraph are the two
   * things a creator page actually needs, and every step beyond that is a
   * sanitiser to maintain and a way for markup to reach the page.
   */
  style: z.enum(["body", "heading"]).default("body"),
});

export const imageBlockSchema = z.object({
  url: storedImageUrl,
  alt: altText,
  /** An image that is also a button. Null means it is just an image. */
  href: urlSchema.nullable().default(null),
  aspect: z.enum(["auto", "square", "wide", "portrait"]).default("auto"),
});

const galleryItemSchema = z.object({
  /*
   * Carried in the JSON because a gallery image is not a row anywhere — it has
   * no clicks to attribute and no life outside its block. Generated by the
   * editor so React keys and reordering stay stable across a save.
   */
  id: z.string().trim().min(1).max(64),
  url: storedImageUrl,
  alt: altText,
  caption,
});

export const galleryBlockSchema = z.object({
  title: z.string().trim().max(60).default(""),
  /*
   * At least one image, because a gallery with none renders as nothing at all
   * and a creator whose save succeeded would have no way to tell. Refusing it
   * is what turns an invisible block into a sentence in the editor.
   */
  items: z.array(galleryItemSchema).min(1, "Add at least one image.").max(24),
  aspect: z.enum(["square", "portrait", "wide"]).default("portrait"),
  cta: callToAction,
});

/** Validated by whether it resolves to a provider, never by pattern alone. */
const providerUrl = (allowed: typeof VIDEO_PROVIDERS) =>
  z
    .string()
    .trim()
    .min(1)
    .max(2048)
    .refine((value) => resolveEmbed(value, allowed) !== null, "That link is not supported.");

export const videoBlockSchema = z.object({
  url: providerUrl(VIDEO_PROVIDERS),
  title: z.string().trim().max(60).default(""),
});

export const embedBlockSchema = z.object({
  url: providerUrl(EMBED_PROVIDERS),
  title: z.string().trim().max(60).default(""),
});

export const dividerBlockSchema = z.object({});

/* ── The data a block of each type carries ────────────────────────────────── */

export type LinksBlockData = z.infer<typeof linksBlockSchema>;
export type SocialsBlockData = z.infer<typeof socialsBlockSchema>;
export type TextBlockData = z.infer<typeof textBlockSchema>;
export type ImageBlockData = z.infer<typeof imageBlockSchema>;
export type GalleryBlockData = z.infer<typeof galleryBlockSchema>;
export type GalleryItem = z.infer<typeof galleryItemSchema>;
export type VideoBlockData = z.infer<typeof videoBlockSchema>;
export type EmbedBlockData = z.infer<typeof embedBlockSchema>;
export type DividerBlockData = z.infer<typeof dividerBlockSchema>;
