-- ShowMe — Smart Optimization
--
-- The last migration of the planned build, and the smallest of the feature
-- migrations, which is the point. Smart Optimization is a reading of analytics
-- that already exist: it derives, it does not collect. There is no second
-- events table, no materialized copy of `page_views` under another name, and
-- nothing here that a creator's page has to write to on every visit.
--
-- Three things:
--
--   1. `analytics_device_performance` — views *and* clicks per device, in one
--      aggregate. The existing `analytics_breakdown` returns views only, and
--      a per-device click-through rate needs both halves measured the same
--      way.
--
--   2. `optimization_events` — what a creator applied and what they dismissed.
--      One small table, one row per decision, holding the previous state so an
--      action can be undone.
--
--   3. `optimize_reorder_links` — applying a recommended order as a single
--      statement rather than as N round trips that can half-finish.
--
-- Everything else the feature needs is computed from the analytics functions
-- Phase 6 already ships, using their definitions of a view, a click and a
-- click-through rate. There is deliberately no second definition of any of
-- those anywhere in this file or in `src/lib/optimize`.

-- ────────────────────────────────────────────────────────────────────────────
-- Views and clicks, per device
-- ────────────────────────────────────────────────────────────────────────────

-- Why device and not source: both tables derive `device` from the user agent
-- of their own request, so a click from a phone is recorded as a click from a
-- phone and the two counts describe the same population. `source` does not
-- work that way — a page view's source comes from `document.referrer`, while a
-- click is recorded by `/go/<id>` whose referrer is the creator's own page,
-- which normalizes to `direct`. Dividing clicks-by-source into views-by-source
-- would produce a column of numbers that look like conversion rates and are
-- arithmetic on a mismatch, so this function does not offer one. See the note
-- at the top of `src/lib/optimize/rules/audience.ts`.
--
-- `full outer join` rather than a left join from views: a device that produced
-- clicks and no views in the window is vanishingly unlikely and would be
-- silently dropped by the wrong join, and a zero that should be a number is
-- the kind of error nobody ever finds.
create or replace function public.analytics_device_performance(
  p_from timestamptz,
  p_to timestamptz
)
returns table (device text, views bigint, clicks bigint)
language sql
stable
security invoker
set search_path = ''
as $$
  with seen as (
    select v.device::text as device, count(*) as n
      from public.page_views v
     where v.created_at >= p_from and v.created_at < p_to
     group by 1
  ),
  clicked as (
    select c.device::text as device, count(*) as n
      from public.link_clicks c
     where c.created_at >= p_from and c.created_at < p_to
     group by 1
  )
  select coalesce(seen.device, clicked.device),
         coalesce(seen.n, 0),
         coalesce(clicked.n, 0)
    from seen
    full outer join clicked on clicked.device = seen.device
   order by 2 desc, 1 asc;
$$;

comment on function public.analytics_device_performance(timestamptz, timestamptz) is
  'Views and clicks per device over a window. security invoker: RLS decides whose events these are.';

revoke all on function public.analytics_device_performance(timestamptz, timestamptz) from public;
grant execute on function public.analytics_device_performance(timestamptz, timestamptz) to authenticated;

-- ────────────────────────────────────────────────────────────────────────────
-- What the creator decided
-- ────────────────────────────────────────────────────────────────────────────

-- A recommendation is never stored. It is recomputed from analytics on every
-- request, which is what makes it impossible for the page to show "move
-- YouTube to #1" after YouTube has been moved to #1 — the situation is gone,
-- so the recommendation is not generated. What *is* stored is the creator's
-- side of the exchange: the ones they applied, so there is a history and an
-- undo, and the ones they dismissed, so they are not asked twice.
--
-- `recommendation_key` is what both hang on. It is generated by the rule from
-- the situation — the type plus the link it concerns — so it is stable across
-- evaluations of the same page and different for a different link. A random
-- id would make "don't show me this again" last exactly one page load.
create table public.optimization_events (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null references public.profiles (id) on delete cascade,

  kind text not null check (kind in ('applied', 'dismissed')),

  -- The rule that produced it. Constrained to the shape of a rule name rather
  -- than to a list, so adding a rule is a TypeScript change and not a
  -- migration — while still refusing anything that is not one.
  recommendation_type text not null check (recommendation_type ~ '^[A-Z][A-Z_]{2,63}$'),
  recommendation_key text not null check (char_length(recommendation_key) between 1 and 200),

  -- What the creator sees in their history. Written by the server from the
  -- recommendation it just applied, never by the client.
  summary text not null check (char_length(summary) between 1 and 300),

  -- Enough of the previous state to put it back. Null for a dismissal, and
  -- for anything that turns out not to be reversible.
  undo jsonb,
  undone_at timestamptz,

  created_at timestamptz not null default now()
);

comment on table public.optimization_events is
  'One row per optimization a creator applied or dismissed. Holds no analytics — recommendations are recomputed from the event tables on every request.';
comment on column public.optimization_events.recommendation_key is
  'Stable identity of the situation, generated by the rule. Dismissals are keyed on it.';
comment on column public.optimization_events.undo is
  'The previous state of the affected rows, written by the server. Null when the action is not reversible.';

-- The history query: this creator's rows, newest first.
create index optimization_events_profile_created_idx
  on public.optimization_events (profile_id, created_at desc);

-- Dismissing twice is the same as dismissing once. A partial unique index
-- makes that true in the database rather than in whichever caller remembers.
create unique index optimization_events_dismissed_key
  on public.optimization_events (profile_id, recommendation_key)
  where kind = 'dismissed';

alter table public.optimization_events enable row level security;

-- The whole policy set, and it is the same shape as every other owned table in
-- this schema: a creator's own rows, and nothing else. There is no public
-- read policy of any kind — an optimization score is a private number about a
-- private dashboard, and a visitor to a creator's page must never be able to
-- learn it.
create policy "owners read their optimization events"
  on public.optimization_events for select
  to authenticated
  using (profile_id = (select auth.uid()));

create policy "owners record their optimization events"
  on public.optimization_events for insert
  to authenticated
  with check (profile_id = (select auth.uid()));

-- Update exists for exactly one field — `undone_at` — and delete for undoing a
-- dismissal. Both are still whole-row policies because a column-level grant
-- would be a second mechanism saying the same thing less visibly.
create policy "owners update their optimization events"
  on public.optimization_events for update
  to authenticated
  using (profile_id = (select auth.uid()))
  with check (profile_id = (select auth.uid()));

create policy "owners delete their optimization events"
  on public.optimization_events for delete
  to authenticated
  using (profile_id = (select auth.uid()));

-- ────────────────────────────────────────────────────────────────────────────
-- Applying an order
-- ────────────────────────────────────────────────────────────────────────────

-- Reordering four links is one decision a creator made, and four `update`
-- statements from the application would let a dropped connection leave a page
-- in an order nobody chose. This is the same reasoning that made `save_page` a
-- single function in Phase 4, and it is the same solution.
--
-- Two things it deliberately cannot do.
--
-- It cannot move a link between blocks. `block_id` is not a parameter, so a
-- recommendation can reorder a section and can never quietly lift a link out
-- of "Shop" into "Latest" — which would be rearranging a creator's page rather
-- than reordering it, and would also be the one place a crafted payload could
-- name another creator's block.
--
-- It cannot touch a row it does not own. `security invoker` means Row Level
-- Security applies to the `update` exactly as it would from anywhere else, and
-- the explicit `profile_id = me` beside it is the belt to that braces: a
-- payload naming another creator's link ids matches nothing and changes
-- nothing, and the returned count says so.
create or replace function public.optimize_reorder_links(p_order jsonb)
returns integer
language plpgsql
security invoker
set search_path = ''
as $$
declare
  me uuid := (select auth.uid());
  touched integer;
begin
  if me is null then
    raise exception 'not_authenticated' using errcode = 'insufficient_privilege';
  end if;

  update public.links l
     set position = o.position
    from (
      select (e ->> 'id')::uuid as id,
             (e ->> 'position')::int as position
        from jsonb_array_elements(coalesce(p_order, '[]'::jsonb)) e
    ) o
   where l.id = o.id
     and l.profile_id = me;

  get diagnostics touched = row_count;
  return touched;
end;
$$;

comment on function public.optimize_reorder_links(jsonb) is
  'Apply a new position to several of the calling user''s own links in one statement. Cannot move a link between blocks. security invoker: RLS applies.';

revoke all on function public.optimize_reorder_links(jsonb) from public;
grant execute on function public.optimize_reorder_links(jsonb) to authenticated;
